services:
  github-runner:
    image: runner:latest
    container_name: github-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount persistent data into a subdirectory so that /home/docker (with runner files) isn’t overwritten.
      - ./runner-data:/home/docker/data
    env_file:
      - .env
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
